// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Navigation: typeof import('./src/components/nav/Navigation.vue')['default']
    PixiGame: typeof import('./src/components/PixiGame.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}

export { }
